# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :microserviceA do |server|
    server.vm.box = "centos1706_v0.3.0_rabbitmq_sensu_ga"
    server.vm.network :private_network, ip: "192.168.56.102"
    #server.vm.network "public_network", bridge: "eno1", ip:"192.168.131.24", netmask: "255.255.255.0"
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1048","--cpus", "1", "--name", "microserviceA" ]
    end
      config.vm.provision "shell", path: "config_microserviceA.sh"
  end
end
